cas.client.mode=resource-server
cas.client.business-login-proxy.enabled=false
cas.client.token-auth.enabled=true
cas.client.redirect-login=false
cas.client.use-session=false
cas.client.slo.enabled=false
